### ISSUE TITLE
#2 export DB schema and share to the team

### ISSUE THREAD

**Issue by JulienL-Deca** [Martin3418/sharepayByJJMM#2]
1- when the tables are created : export them in csv & SQL dump
2- share the csv and dump to the team via slack or directly in this issue

**Comment by MattDeback** [comment]
please find enclosed the dump document
[dump.txt](https://github.com/Martin3418/sharepayByJJMM/files/2001006/dump.txt)
dont forget to rename it in SQL

**Comment by MattDeback** [comment]
pg_dump shareplayJJMM > dump.sql

**Comment by JulienL-Deca** [comment]
pur la base de données en local il faut

1- créer la base de données local
  createdb shareplayJJMM

2- créer les tables à partir du dump.txt
  psql shareplayJJMM < dump.txt

et voilà !
